In [25]:
import pandas as pd
df=pd.read_csv("/Users/nirbhaysedha/Documents/SVM/train.csv")

In [26]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
df2=pd.read_csv('/Users/nirbhaysedha/Documents/SVM/sample_submission.csv')

In [28]:
df2.isnull().sum()

ImageId    0
Label      0
dtype: int64

In [29]:
df = pd.concat([df, df2], ignore_index=True)

In [30]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import KernelPCA,PCA
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report
from sklearn.model_selection import train_test_split,cross_val_score

In [31]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,ImageId,Label
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
3,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN

In [32]:
x=df.iloc[:,:-1]

In [54]:
y=df.iloc[:,-1]
y=y.fillna(1)

In [55]:
df['Label'].unique()

array([nan,  0.])

In [56]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=90)

In [57]:
imputer=SimpleImputer()
x_train = imputer.fit_transform(x_train)
x_test=imputer.transform(x_test)

In [58]:
scaling=StandardScaler()
x_train=scaling.fit_transform(x_train)
x_test=scaling.transform(x_test)

In [59]:
Dimension_Red=PCA()
x_train_tr=Dimension_Red.fit_transform(x_train)
x_test_tr=Dimension_Red.transform(x_test)

In [ ]:
Dimension_Red=KernelPCA()
x_train_tr=Dimension_Red.fit_transform(x_train)
x_test_tr=Dimension_Red.transform(x_test)

In [61]:
model=SVC(kernel='rbf')
model.fit(x_train_tr,y_train)
prediction=model.predict(x_test_tr)
print("accuracy_score is ",accuracy_score(y_test,prediction))
print(classification_report(y_test,prediction))

accuracy_score is  1.0
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      5569
         1.0       1.00      1.00      1.00      8431

    accuracy                           1.00     14000
   macro avg       1.00      1.00      1.00     14000
weighted avg       1.00      1.00      1.00     14000